### DISCUSSION TITLE
DoD

### DISCUSSION THREAD

**Discussion by sotoniak** [mletenay/home-assistant-goodwe-inverter#109] [Q&A] [answered]

**Comment by tinuva** [comment, marked as answer]
> Hey. Hey,
>I need to set DOD to 0 using a script. Can someone please advise me how to do this? When I set number.depth_of_discharge_on_grid the change is not transferred to GoodWe. Only if I make the change manually in Home Assistant.

Are you sure?

When I test the following in the development tools, in the services section, it works no problem.
```
service: number.set_value
data:
  value: 0
target:
  entity_id: number.depth_of_discharge_on_grid
```
