### DISCUSSION TITLE
GW5048D-ES - action: goodwe.get_parameter for ECO MODE POWER

### DISCUSSION THREAD

**Discussion by pjpeartree** [mletenay/home-assistant-goodwe-inverter#313] [Q&A]
Hi everyone,

I’m experiencing an issue with my GW5048D-ES inverter where it sometimes doesn’t register the ECO MODE Power value when I call the action to set it. I’m using the following service call:

```yaml
service: number.set_value
alias: "Set Inverter Eco Mode Power"
data:
  value: 80 
target:
  entity_id: number.eco_mode_power
```

However, there are times when the inverter does not assume this value. I would like to confirm whether the change was successful by using the get_parameter service, but no luck so far, maybe the parameter name is incorrect? Something like:

```yaml
action: goodwe.get_parameter
data:
  parameter: eco_mode_power
  device_id: 09bb9279d5e32159183ffc7c0c2517c2
  entity_id: input_number.inverter_eco_mode_power
```

Has anyone else faced a similar issue or have suggestions on how to reliably verify that the value has been set correctly? Any insights would be greatly appreciated!

Thanks in advance!
