### ISSUE TITLE
Power Export Limit - ET series inverter

### ISSUE THREAD

**Issue by TomEkk33** [mletenay/home-assistant-goodwe-inverter#167]
Hello @mletenay,

Power Export limit  value written by HA is always updated in related ET Inverter's register, which is OK.
![image](https://user-images.githubusercontent.com/121716844/221439586-81330c8b-c5b5-4e82-a5f6-4608b216e5ba.png)

However when Power Export limit is **disabled** in PV Master
<img src="https://user-images.githubusercontent.com/121716844/221439502-15f91f8d-4837-43dd-92d2-b5a69f5b22a3.png" width=300>

HA does **not activate** "Power Export limit" during such write.

Please add option to explicitly enable/disable "Power Export limit" in HA. 
<img src="https://user-images.githubusercontent.com/121716844/221439978-7874c644-70d5-4fa8-8659-8a86650645c8.png" width=300>

**Comment by mletenay** [comment]
I'm somehow reluctant to add yet another switch to HA UI which vast majority of users do not need.
But as mentioned in https://github.com/home-assistant/core/issues/88963, you can turn the power limit switch by invoking "set_parameter" HA service with "grid_export" and 0/1

**Comment by TomEkk33** [comment]
> get_parameter/set_parameter services

That's perfect. Thanks a lot.
Adding advanced features with call service as a general rule is excellent option. 
It does not introduce confusion to typical users.

**Comment by petrrysavy74** [comment]
Exactly such a solution would be perfect for me. But I'm just a beginner. I don't know how to practically do the above procedure with get_parameter/set_parameter services "grid_export" setting on or off (0/1). Can you please help a beginner? Maybe send modified configuration files. I have the Goodwe experimental integration installed, it has really moved me forward in managing grid flows. The grid_export ON/OFF switch is important to me. I have a GW3600S-BP which is a retrofit inverter without a PV part and solves the balancing of the grid at the house output. Therefore, it has slightly different requirements than a regular FVE hybrid inverter. Thanks

**Comment by TomEkk33** [comment]
@petrrysavy74

Below is a simple automation to turn off export power limit - be careful doing this.
```
alias: Goodwe_export_power_10kW
trigger: []
condition: []
action:
  - device_id: 47dcf029199ae1b3f5bcf99a51506445
    domain: number
    entity_id: number.grid_export_limit
    type: set_value
    value: 10000
  - service: goodwe.set_parameter
    data:
      device_id: 47dcf029199ae1b3f5bcf99a51506445
      parameter: grid_export
      value: 0
mode: single
```

Navigate in HA to "Settings -> Automations & Scenes -> create automation"
![obraz](https://user-images.githubusercontent.com/121716844/234283410-c17e19c0-411a-4828-9e34-97bba35dd5a1.png)
![obraz](https://user-images.githubusercontent.com/121716844/234283685-0f3da2e8-5822-4421-975b-312030fd7067.png)
![obraz](https://user-images.githubusercontent.com/121716844/234283790-9fa54e57-4947-4942-8da8-7e899e1d9ed4.png)

switch to "Edit in YAML" & paste the above code.

![obraz](https://user-images.githubusercontent.com/121716844/234283974-d62e87f7-e281-4016-96e6-a5f7c2edb118.png)

Then switch to visual mode. Update parameters in this mode if needed. Then save automation.

device_id - should be your inverter ID

To enable power limit to e.g. 100 W just change
```
    entity_id: number.grid_export_limit
    type: set_value
    value: 100

      parameter: grid_export
      value: 1
```

This automation was used for ET inverter type. I don't know other inverters.

Once gain setting incorrect values might give unpredictable results to your inverter. 
You can always check the results using PV Master/SolarGo application dedicated to your inverter

**Comment by jl1990** [comment]
Not working for me neither. I have a GW5048-EM inverter, I added the experimental HACS version of this repo.
I can read values correctly, but setting them up does not seem to be working

**Comment by mirecekd** [comment]
Works for me with v0.9.9.11
I have helper `input_boolean.fve_export_limit` which calls this automation:
```
alias: FVE nastavit grid_export
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.fve_export_limit
condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.fve_export_limit
        state: "on"
    then:
      - service: goodwe.set_parameter
        data:
          device_id: putyoursdeviceid
          parameter: grid_export
          value: 1
    else:
      - service: goodwe.set_parameter
        data:
          device_id: putyoursdeviceid
          parameter: grid_export
          value: 0
mode: single
```
you can than put `input_boolean.fve_export_limit` to lovelaco or use (for example) in automation. I am using it to disallow export on negative spot prices -


disallow export
```
alias: FVE - vypnout přetoky - ENTRI výkup pod 0
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.entri_aktualni_vykup
    below: -0.25
condition: []
action:
  - service: number.set_value
    data:
      value: "100"
    target:
      entity_id: number.grid_export_limit
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.fve_export_limit
  - service: notify.telegram_mirecek
    data:
      message: >-
        Cena spotu od Entri je *menší* než -0.25 Kč/kWh - *vypínám* přetoky
      title: Zpráva od FVE
mode: single
```


allow export
```
alias: FVE - zapnout přetoky - ENTRI výkup nad 0
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.entri_aktualni_vykup
    above: -0.25
condition: []
action:
  - service: number.set_value
    data:
      value: "10000"
    target:
      entity_id: number.grid_export_limit
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.fve_export_limit
  - service: notify.telegram_mirecek
    data:
      message: >-
        Cena spotu je *větší* než -0.25 Kč/kWh - *zapínám* přetoky
      title: Zpráva od FVE
mode: single
```
