### ISSUE TITLE
"Today Buy" and/or "Today Load Consumption" are missing for ET series

### ISSUE THREAD

**Issue by schamock** [mletenay/home-assistant-goodwe-inverter#17]
Hi,
I have an ET series inverter and came across this project. With your script I can get the values for todays PV generation and the todays sell total (and indirectly todays self use as Gen - Sell).
But unfortunately the values for todays total buy and/or todays load consumption are missing (I can see them in the SEMS App).
Is there a way to get at least one of those values? One would be enough as Load Consumption = Self Use + Buy

Thanks a lot!

**Comment by mletenay** [comment]
Well, such data are not directly available.
The inverter only provides "immediate" or snapshot values.
The only 2 exceptions are the daily and total PV production, for those the inverter maintains its cumulative  counters.
(The daily reset on midnight).
What SEMS portal displays is actually some aggregate function of these snapshot values kept in its own database.
However something similar can also be done on HomeAssistant level, I'll provide examples soon.

**Comment by wishie** [comment]
You need to add sensors as integration sensors, and then use utility_meter integration to create the daily/monthly sensors..

```
- platform: integration                  
  source: sensor.goodwe_solar_total                                    
  name: energy_pv                        
  unit_prefix: k                         
  round: 3                               
- platform: integration                                                  
  source: sensor.goodwe_house_consumption
  name: energy_house                  
  unit_prefix: k             
  round: 3                                                            
- platform: integration       
  source: sensor.goodwe_pgrid                 
  name: energy_grid
  unit_prefix: k                                                         
  round: 3             




utility_meter:                                                                                                                                          
  pv_daily:                                                                                                                                             
    source: sensor.energy_pv                                                                                                                            
    cycle: daily                                                                                                                                        
  pv_monthly:                                                                                                                                           
    source: sensor.energy_pv                                                                                                                            
    cycle: monthly                                                                                                                                      
  house_daily:                                                                                                                                          
    source: sensor.energy_house                                                                                                                         
    cycle: daily                                                                                                                                        
  house_monthly:                                                                                                                                        
    source: sensor.energy_house                                                                                                                         
    cycle: monthly                                                                                                                                      
  grid_daily:                                                                                                                                           
    source: sensor.energy_grid                                                                                                                          
    cycle: daily                                                                                                                                        
    net_consumption: true                                                                                                                               
  grid_monthly:                                                                                                                                         
    source: sensor.energy_grid                                                                                                                          
    cycle: monthly                                                                                                                                      
    net_consumption: true 
```
