### ISSUE TITLE
Issue with more than 1 inverter.

### ISSUE THREAD

**Issue by wishie** [mletenay/home-assistant-goodwe-inverter#4]
I have 2 x GoodWe GW5048-EM inverters. When setting them up in Home Assistant with the following config:

```
sensor:                                                  
  - platform: goodwe                                     
    ip_address: 192.168.100.6                            
    scan_interval: 30                                    
    sensor_name_prefix: Inverter1                  
  - platform: goodwe                                     
    ip_address: 192.168.100.22                     
    scan_interval: 30                                    
    sensor_name_prefix: Inverter2
```

I do not get 2 sets of sensors as expected.

Below is list of sensors found in HA for the above config:
![Screen Shot 2020-09-21 at 9 06 58 am](https://user-images.githubusercontent.com/635844/93746305-396c7a00-fc38-11ea-8638-5726e1849743.png)
