### ISSUE TITLE
Battery Sensor for Energy Management Panel

### ISSUE THREAD

**Issue by SloppolS** [mletenay/home-assistant-goodwe-inverter#77]
Hi,

thanks for this integration, works very well.

After some work, I now succeeded in adding the sensors for grid consumption and solar production to the energy management panel. Works great.

But I'm not sure how to add the Battery. I need kwh to battery and kwh from battery, maybe in combination with the `utility_meter:`
But I cant find a sensor, that delivers the required values.
I there any way, to get this to work? 
I using an EM Inverter.

Thanks a lot.

**Comment by chemuki205** [comment]
Hi, this is working for me

```
template:
  - sensor:
    - name: goodwe_battery_charge
      unit_of_measurement: W
      state_class: measurement
      device_class: power
      state: >
        {% if is_state('sensor.goodwe_battery_mode', '3') %}
          {{ states('sensor.goodwe_pbattery1')|float * -1}}
        {% else %}
          {{ 0 }}
        {% endif %}

    - name: goodwe_battery_discharge
      unit_of_measurement: W
      state_class: measurement
      device_class: power
      state: >
        {% if is_state('sensor.goodwe_battery_mode', '2') %}
          {{ states('sensor.goodwe_pbattery1')|float}}
        {% else %}
          {{ 0 }}
        {% endif %}

sensor:
  - platform: integration
    source: sensor.goodwe_battery_charge
    name: goodwe_battery_charge_sum
    unit_prefix: k
    round: 3
    method: left

  - platform: integration
    source: sensor.goodwe_battery_discharge
    name: goodwe_battery_discharge_sum
    unit_prefix: k
    round: 3
    method: left
```
